[SddmTheme]
Name=ii-pixel
Description=iNiR SDDM login screen — Material You dynamic colors
Type=sddm-theme
Author=iNiR project
Version=1.0
Website=https://github.com/snowarch/iNiR
Screenshot=
MainScript=Main.qml
ConfigFile=theme.conf

[General]
background=assets/background.png
defaultBackground=assets/background.png
blurRadius=50

# iNiR Material You colors — updated automatically by sync-pixel-sddm.py on wallpaper change
primaryColor=#38BDF8
onPrimaryColor=#121625
surfaceColor=#1e293b
surfaceContainerColor=#121625
onSurfaceColor=#ffffff
onSurfaceVariantColor=#81C7F5
backgroundColor=#121625
errorColor=#FF5E85
materialShapeChars=false
